feat: add controllers for user and item
Brill1983/java-shareit pull request #1
Opened 2023-08-19 10:12 UTC by Brill1983

2023-08-19 11:52 UTC, Frilock requested changes
Добрый день, работу посмотрел, комментарии оставил

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto saveItem(@RequestHeader("X-Sharer-User-Id") long userId, @RequestBody @Valid ItemDto itemDto) {
X-Sharer-User-Id - литерал используется более 2х раз, вынесите его в константу (static final)

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        userRepository.getUserById(userId).orElseThrow(() -> new UserNotFoundException("Пользователь с ID " + userId + " не зарегистрирован"));
.orElseThrow лучше перенести на следующую строчку, слишком длинная строка

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        userRepository.getUserById(userId).orElseThrow(() -> new UserNotFoundException("Пользователь с ID " + userId + " не зарегистрирован"));
аналогично

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        Item itemFromPer = itemRepository.getItemById(itemId).orElseThrow(() -> new ItemNotFoundException("Предмета с ID " + itemId + " не зарегистрировано"));
тут и. в других местах аналогично

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return itemsList.stream()
можно заинлайнить return itemRepository.getUserItems(userId).stream

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +    Long itemIdCounter = 0L;
Отсутствует модификатор

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +        if (item.getName() != null) {
Можно такие конструкции заменять на Optional.ofNullable(item.getName()).ifPresent(itemFromRep::setName)

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +        if (itemRepository.containsKey(itemId)) {
Можно заменить на тернарное выражение - будет компактнее

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +            if ((item.getName().toLowerCase().contains(text.toLowerCase()) ||
Лучше использовать StringUtils.containsIgnoreCase

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dao/UserRepositoryImp.java
> +    long userCounter = 0L;
модификатор

2023-08-19 11:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dao/UserRepositoryImp.java
> +        if (userRepository.containsKey(id)) {
можно на тернарник заменить

2023-08-19 12:40 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto saveItem(@RequestHeader("X-Sharer-User-Id") long userId, @RequestBody @Valid ItemDto itemDto) {
Исправил

2023-08-19 12:40 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        userRepository.getUserById(userId).orElseThrow(() -> new UserNotFoundException("Пользователь с ID " + userId + " не зарегистрирован"));
Сделал

2023-08-19 12:40 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        userRepository.getUserById(userId).orElseThrow(() -> new UserNotFoundException("Пользователь с ID " + userId + " не зарегистрирован"));
Сделал

2023-08-19 12:40 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        Item itemFromPer = itemRepository.getItemById(itemId).orElseThrow(() -> new ItemNotFoundException("Предмета с ID " + itemId + " не зарегистрировано"));
Сделал

2023-08-19 12:40 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return itemsList.stream()
Сделал

2023-08-19 12:40 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +    Long itemIdCounter = 0L;
Исправил

2023-08-19 12:41 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +        if (item.getName() != null) {
Спасибо! Классный способ, беру на вооружение.

2023-08-19 12:41 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +        if (itemRepository.containsKey(itemId)) {
Сделал

2023-08-19 12:41 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +            if ((item.getName().toLowerCase().contains(text.toLowerCase()) ||
Сделал

2023-08-19 12:41 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/user/dao/UserRepositoryImp.java
> +    long userCounter = 0L;
Исправил

2023-08-19 12:42 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/user/dao/UserRepositoryImp.java
> +        if (userRepository.containsKey(id)) {
Сделал

2023-08-20 10:48 UTC, Frilock approved these changes
Принято

2023-08-20 10:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public static final String HEADER = "X-Sharer-User-Id";
почему public? Вроде нигде больше не используется

2023-08-20 19:07 UTC, merged