Add item requests
Brill1983/java-shareit pull request #3
Opened 2023-09-21 19:59 UTC by Brill1983

2023-09-22 07:26 UTC, Frilock requested changes
Добрый день, работу посмотрел, пару комментариев оставил

2023-09-22 07:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +    List<Booking> findBookingsByBooker_IdOrderByStartDesc(Long bookerId, Pageable page);
Логичнее было бы возвращать обьект Page, там где вы работаете с pageable

2023-09-22 07:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("В метод getUserItems передан userId {}, индекс первого элемента {}, количество элементов на странице {}", userId, from, size);
слишком длинна строка, перенесите аргументы на другую строку

2023-09-22 07:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Booking lastBookings = bookingRepository.findFirstByItem_IdAndStartBeforeAndStatusOrderByStartDesc(itemId, LocalDateTime.now(), Status.APPROVED)
Слишком длинные строки

2023-09-22 07:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/RequestMapper.java
> +
лишняя пустая строка

2023-09-22 07:26 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private final UserServiceImpl userService;
Правильнее внедрять интерфейсы, а не реализации, то есть в данном случае просто UserService

2023-09-22 07:26 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +
Лишняя пустая строка

2023-09-22 07:44 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private final UserServiceImpl userService;
Поправил.

2023-09-22 07:45 UTC, Brill1983 commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +
Исправил

2023-09-22 07:46 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/request/RequestMapper.java
> +
Исправил

2023-09-22 08:08 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Booking lastBookings = bookingRepository.findFirstByItem_IdAndStartBeforeAndStatusOrderByStartDesc(itemId, LocalDateTime.now(), Status.APPROVED)
Исправил

2023-09-22 08:08 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("В метод getUserItems передан userId {}, индекс первого элемента {}, количество элементов на странице {}", userId, from, size);
Исправил

2023-09-22 08:38 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +    List<Booking> findBookingsByBooker_IdOrderByStartDesc(Long bookerId, Pageable page);
Исправил

2023-09-22 18:29 UTC, Frilock approved these changes
Принято

2023-09-22 18:29 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>                          .stream()
Вообще проще было бы сделать 1 ретурн в конце метода и там преобразовывать Page в лист, а то вы так в каждом case блоке делаете. Не оптимально

2023-09-23 06:04 UTC, Brill1983 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>                          .stream()
Исправил

2023-09-23 06:21 UTC, merged