Add docker
Brill1983/java-shareit pull request #4
Opened 2023-10-01 17:39 UTC by Brill1983

2023-10-02 20:15 UTC, Frilock requested changes
Добрый день, отличная работа, из комментариев:
1. Убрать закоментированный код
2. Тесты валидации, которые вы удаляете из подмодуля сервера, нужно перенести в gateway

2023-10-02 20:15 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/service/ErrorHandler.java
> +//    @ExceptionHandler
закоментированный код надо убрать

2023-10-02 21:39 UTC, Brill1983 commented on server/src/main/java/ru/practicum/shareit/service/ErrorHandler.java
> +//    @ExceptionHandler
Исправил

2023-10-03 06:01 UTC, Frilock approved these changes
Супер, принято

2023-10-04 08:21 UTC, merged